/**
 * Sample PSBT/TX data extracted from test fixtures.
 * Auto-generated by scripts/extract-samples.js
 * DO NOT EDIT MANUALLY
 */
export interface Sample {
    name: string;
    type: "psbt" | "tx";
    data: string;
}
export declare const samples: Sample[];
