[package]
name = "wasm-utxo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[lints.clippy]
all = "warn"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
miniscript = { git = "https://github.com/BitGo/rust-miniscript", tag = "miniscript-12.3.4-opdrop" }
bech32 = "0.11"

[dev-dependencies]
base64 = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"

[profile.release]
# this is required to make webpack happy
# https://github.com/webpack/webpack/issues/15566#issuecomment-2558347645
strip = true
