[package]
name = "wasm-utxo-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wasm-utxo-cli"
path = "src/main.rs"

[dependencies]
wasm-utxo = { path = ".." }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
hex = "0.4"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num-bigint = "0.4"
bitcoin = "0.32"
colored = "2.1"
ptree = "0.5"
